### PR TITLE
Adding assets2 and moving all external links to the static assets.

### LINKED ISSUE #225: Support disconnected network installation
Some of contents in pathfinder-ui module have external links of js and css resources. This means that PathFinder does not work in the disconnected network environments.

We hope that PathFinder is improved to include all the js and css resources in the war module.

./viewAssessment.jsp:

```
 15         <!-- #### CHARTS DEPENDENCIES ### -->
 16         <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
```

./head.jsp:

```
  9     <link rel="stylesheet" href="https://rawgit.com/RedHatBrand/Overpass/master/webfonts/overpass-webfont/overpass.css"/>

 15           <script src="https://www.w3counter.com/tracker.js?id=129401"></script>
```

./datatables-dependencies.jsp:

```
 6   <script src="https://cdn.datatables.net/v/bs/dt-1.10.18/datatables.min.js"></script>
```

./report.jsp:

```
 20         <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>
 21         <script src="https://unpkg.com/lodash@4.17.10/lodash.min.js"></script>
```

./survey.jsp:

```
 33             <script src="https://unpkg.com/jquery"></script>
 34                                 
 35             <script src="https://surveyjs.azureedge.net/1.0.23/survey.jquery.js"></script>
 36             <link href="https://surveyjs.azureedge.net/1.0.23/survey.css" type="text/css" rel="stylesheet"/>
 37             <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
 38           <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
 39                 

 43             <script src="https://unpkg.com/surveyjs-widgets"></script>

 47             <script src="https://unpkg.com/icheck@1.0.2"></script>
 48             <link rel="stylesheet" href="https://unpkg.com/icheck@1.0.2/skins/square/blue.css">
```

### PR DESCRIPTION
**Pull request by ianwatsonrh**
Fixes #225 

NPM is used to create assets2 in the first place.

If approach is accepted we can use NPM to create all assets. 

w3counter tracker is not placed in static assets as this will not work in a disconnected instance

### CODE REVIEW

**Comment by noelo** [comment]
@ianwatsonrh does this break the w3counter functionality ? I understand it won't work in a disconnected environment

**Comment by ianwatsonrh** [comment]
@noelo The javascript code injected via https://www.w3counter.com/tracker.js?id=129401 injects code that will send analytic information to the external w3counter api endpoint. 

As the analytic requests wont work in a disconnected environment, as they wont be able to hit the w3counter api endpoint, I think its sufficient to also leave this in as an external source.

This will result in a single failure to load the src rather than repeated failures that the endpoint is unreachable during application use

**Comment by ianwatsonrh** [comment]
@noelo changed this to merge to disconnected branch

**Comment by noelo** [comment]
@ianwatsonrh thanks. Much appreciated

**Pull request merged**
